export default {
  apps: [
    {
      name: "maptile-proxy",
      script: "dist/src/index.js",
      instances: "max",
      exec_mode: "cluster",
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
        PORT: 5000,
        MAP_SOURCE: "http://wprd0{1-4}.is.autonavi.com/appmaptile?x={x}&y={y}&z={z}&lang=zh_cn&size=1&scl=1&style=8",
        CACHE_MAX_SIZE: 200,
        CACHE_RESET_INTERVAL: 60000,
        TILE_LOAD_TIMEOUT: 30000,
        LOG_LEVEL: "info",
      },
      env_production: {
        NODE_ENV: "production",
        PORT: 5000,
        MAP_SOURCE: "http://wprd0{1-4}.is.autonavi.com/appmaptile?x={x}&y={y}&z={z}&lang=zh_cn&size=1&scl=1&style=8",
        CACHE_MAX_SIZE: 200,
        CACHE_RESET_INTERVAL: 60000,
        TILE_LOAD_TIMEOUT: 30000,
        LOG_LEVEL: "info",
      },
      error_file: "./logs/err.log",
      out_file: "./logs/out.log",
      log_file: "./logs/combined.log",
      time: true,
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: "10s",
      kill_timeout: 5000,
      listen_timeout: 3000,
      node_args: [
        "--max-old-space-size=3072",
        "--optimize-for-size",
      ],
    },
  ],
};
